exp0/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^manage', manage, name='manage'),
    url(r'^viewSummary', viewSummary, name='viewSummary'),
    url(r'^dlSummary', dlSummary, name='dlSummary'),
    url(r'^activateExperiment', activateExperiment, name='activateExperiment'),
    url(r'^deleteExperiment', deleteExperiment, name='deleteExperiment'),
    url(r'^dupliExperiment', dupliExperiment, name='dupliExperiment'),
    url(r'^setParameter', setParameter, name='setParameter'),
    url(r'^delParameter', delParameter, name='delParameter'),
    url(r'^delRecord', delRecord, name='delRecord'),
    url(r'^remoteLab', remoteLab, name='remoteLab'),
    url(r'^recordParams', recordParams, name='recordParams'),
    url(r'^readParams', readParams, name='readParams'),
    url(r'^imageWebcam', imageWebcam, name='imageWebcam'),
    url(r'^programWithParams', programWithParams, name='programWithParams'),
    url(r'^deleteExpRecord', deleteExpRecord, name='deleteExpRecord'),
    url(r'^viewExpRecord', viewExpRecord, name='viewExpRecord'),
    url(r'^listExpRecords', listExpRecords, name='listExpRecords'),
]

mensu/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

from .views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/profile/$', makeProfile, name="makeProfile"),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^exp0/', include('exp0.urls')),
    url(r'^$', home, name='home'),
    url(r'^about', about, name='about'),
    url(r'^manual', manual, name='manual'),
    url(r'^license', license, name='license'),
    url(r'^activate/(?P<uidb64>[\w]+)-(?P<token>[-:\w]+)', activate, name='activate'),
#    url(r'', p404, name="404"),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exp0/models.py
from django.utils.translation import gettext as _
from django.utils.text import mark_safe
from django.db import models
from django.contrib.auth.models import User

import os, json, re

from mensu.settings import BASE_DIR, VIDEO_URL, VIDEO_ROOT

# Create your models here.

class ImageUser(models.Model):
    user=models.ForeignKey(User)
    image=models.FileField(upload_to='images')
    
class Experiment(models.Model):

    """
    When there are more than 1 Eyes17 box, each one is identified
    by a number. The same holds for webcams (only when there will be
    some reliable way to give numbers to devices in a reliable way
    across reboots)
    """
    box = models.IntegerField(
        verbose_name=_("Box number"),
        default=1
    )

    """
    The owner of the experiment (she must be part of the group "scientist"
    """
    owner = models.ForeignKey(User)
    
    """
    Experiments have a one-to-many relationship with Parameters
    no field here so far, as class Parameter has a foreign key to Experiment
    """

    """
    Experiments have a one-to-many relationship with Timeslots
    no field here so far, as class Timeslot has a foreign key to Experiment
    """

    """
    Experiments have one result: a matrix of numbers, which is collected
    during a predefined time, repeteadly with some delay. The property
    channels bears the list of channels which are measured; the
    zeroth one is implicitely the time.
    """
    channels=models.CharField(max_length=50)

    """
    Duration for an experimental session (when a visitor will be able to
    play with the experiment).
    """
    sessionDuration=models.IntegerField()

    """
    Duration of a single measurement, which is made when the visitor
    clicks the "GO" button.
    """
    duration=models.FloatField()

    """
    Number of time intervals for the measurement (for N intervals, the
    number of measurements should be N+1). This way to specify the delay
    between successive measurements makes it easier for one to get simple
    date values in the returned matrix of numbers.
    """
    nInterval=models.IntegerField()

    """
    Title of the experiment. No longer than a tweet message!
    """
    title = models.CharField(max_length=140)

    """
    Summary of the experiment. It must be the name of a file
    which will be edited in Restructured Text format. The file name
    should remain short, and managed completely at instance creation time.
    Two summaries cannot share the same file.
    """
    summary=models.CharField(max_length=25)

    """
    Python code of the experiment. Modifiable parameters must be
    written as PARAMn, where n is a number (i.e. PARAM0, PARAM1, ...
    PARAM9). When a visitor clicks on the "GO" button, parameters
    are set from the form she filled.
    """
    python=models.TextField()

    """
    An experiment among the complete collection can be selected as
    active.
    """
    active=models.BooleanField(default=False)

    def __str__(self):
        return self.title

    @property
    def summaryHtmlUrl(self):
        """
        provide an Url to get the styled HTML of the summary
        """
        return "/exp0/viewSummary?rst="+self.summary

class Parameter(models.Model):
    """
    Defines an experiment parameter; each one is described by
    properties relative to Eyes17's features
    """

    """
    Link to the parent Experiment instance
    """
    exp = models.ForeignKey(Experiment)

    """
    Name of the symbol to be controlled
    """
    symbol = models.CharField(max_length=4)

    """
    Minimum allowed value
    """
    minval = models.FloatField()

    """
    Maximum allowed value
    """
    maxval = models.FloatField()

    """
    Optional property. Some outputs can have an optional property,
    like WG, which can be triangle, a sine wave or come from a given
    wave table
    """
    option = models.CharField(max_length=50, default="", blank=True)

    """
    Optional property. useful to comment the very short symbol name
    """
    comment = models.CharField(max_length=150, default="", blank=True)

    def __str__(self):
        # Translators: symbol is some short string, exp is for some experiment
        return _("{symbol} for {exp}").format(symbol=self.symbol, exp=self.exp)

    @property
    @mark_safe
    def widget(self):
        """
        provides the HTML code for a widget which will allow visitors
        to modify the parameter interactively
        """
        helpStr=(_("You can tune the values precisely by editing them in this text field."))
        dataSet="""
data-vmin="{minval}" data-vmax="{maxval}" data-sep="{sep}"\
""".format(minval=self.minval, maxval=self.maxval, sep=_("to"))
        if "range" in self.option:
            dataSet+=" data-range='true'"
        if "log" in self.option:
            dataSet+=" data-log='true'"
        html="""\
<input type="text" class="paramWidget" {dataSet} title="{helpStr}" id="{s}" />\
""".format(dataSet=dataSet, helpStr=helpStr, s=self.symbol)
        return html

class ParamSetting(models.Model):
    """
    to keep a record of parameters settings as a list (which can contain
    sublists) of numeric values.
    """
    owner = models.ForeignKey(User)
    exp   = models.ForeignKey(Experiment)
    name   = models.CharField(max_length=25)
    whenCreated = models.DateTimeField(auto_now=True)
    values = models.CharField(max_length=150)

    def __str__(self):
        return "{n} ({d})".format(n=self.name, d=self.whenCreated.strftime("%Y/%m/%d %H:%M"))

    @property
    @mark_safe
    def widgetReadOnly(self):
        """
        provides the HTML code for a widget which will allow visitors
        to view a parameter set
        """
        dico=json.loads(self.values)
        result=""
        for k in dico:
            param=Parameter.objects.get(exp=self.exp, symbol=k)
            result+="<div title='{c}'><span class='key'>{k}</span><span class='val'>{v}</span></div>".format(c=param.comment, k=k, v=dico[k])
        return result

            
    
class Timeslot(models.Model):
    """
    defines a timeslot when an experiment is booked by a visitor;
    during a timeslot, the visitor will be able to push the "GO" button
    of the experiment at will, and she will be given references to
    records of the experiments.
    """

    """
    Link to the parent Experiment instance
    """
    exp = models.ForeignKey(Experiment)

    """
    Reservation's date
    """
    whenCreated = models.DateTimeField(auto_now=True)

    """
    Begin of the experiment session. The end of the experiment session
    is given by the duration decided by authors of the experiment
    """
    begin =  models.DateTimeField()

    """
    Identification of the visitor. Visitors are prompted to create an account
    as a Django user
    """
    user = models.ForeignKey(User)
    
class ExpRecord(models.Model):
    """
    Collects the data coming from an experiment run with a particular
    set of parameters
    """

    paramSet = models.ForeignKey(ParamSetting)
    whenCreated = models.DateTimeField(auto_now=True)
    stdout = models.TextField()
    stderr = models.TextField()
    videofile = models.CharField(max_length=140)

    def __str__(self):
        return "Experiment recorded: %s" % self.whenCreated

    @property
    def videofileRecoded(self):
        """
        N.B.: due to openCV's limitations, the video file is first
        recorded as MJPG-encoded AVI file, then recoded to V8-encoded
        WEBM file, for a better compression and compatibility with
        HTML readers. Only the WEBM file is stored in the filesystem,
        the AVI file is unlinked as soon as it was recoded.
        """
        return re.sub(r"\.avi$", ".webm", self.videofile)

    @property
    def videoUrl(self):
        """
        gives the URL to download self.videofile
        @return a valid URL served by Mensu.
        """
        return VIDEO_URL+self.videofileRecoded
    
    def delete(self):
        """
        overrides the inherited method, by unlinking the videofile
        additionnally
        """
        models.Model.delete(self)
        videofile = os.path.join(VIDEO_ROOT,self.videofileRecoded)
        if os.path.exists(videofile):
            os.unlink(videofile)
        return
    

exp0/forms.py
from django.utils.translation import gettext as _
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

import os

from .models import Experiment
from .common import SUMMARY_DIR


class LoginForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username', 'password',)
        widgets = { 'password': forms.PasswordInput, }

class ExperimentForm(forms.ModelForm):

    class Meta:
        model=Experiment
        fields = (
            # read-only 'box',
            # read-only 'owner',
            'channels',
            'sessionDuration',
            'duration',
            'nInterval',
            'title',
            'summary',
            'python',
        )
    def clean_channels(self):
        """
        Verify that channels for the measurements are really allowed
        channels
        """
        allowed_channels=set("A1,A2,A3,MIC,IN1".split(","))
        # given channels can be with tabs or spaces, but must be
        # separated by commas.
        given_channels=set([c.strip() for c in self.cleaned_data["channels"].split(",")])
        remaining = given_channels - allowed_channels
        if remaining:
            # there is at least on non-allowed channel remaining
            raise ValidationError(_("Not recognized: `{r}`. Allowed channels are: {l}").format(r=remaining, l=allowed_channels))
        return self.cleaned_data["channels"]

    def clean_sessionDuration(self):
        """
        A session duration must be comprized between 5 and 30 minutes
        """
        mmin=5
        mmax=30
        sd=self.cleaned_data["sessionDuration"]
        if not (mmin*60 <= sd <= mmax*60):
            raise ValidationError(_("This value must be in the interval {smin} to {smax} ({mmin} to {mmax} minutes).").format(smin=mmin*60, smax=mmax*60, mmin=mmin, mmax=mmax))
        return sd

    def clean_duration(self):
        """
        The longest experinment duration is 30 seconds, the shortest is 
        1 millisecond
        """
        smin=1e-3
        smax=30
        s=self.cleaned_data["duration"]
        if not smin<=s<=smax:
            raise ValidationError(_("This value must be in the interval {smin} to {smax}.").format(smin=smin, smax=smax))
        return s
    
    def clean_nInterval(self):
        """
        The intervals are between 1 and 2000
        """
        imin=1
        imax=2000
        i=self.cleaned_data["nInterval"]
        if not imin<=i<=imax:
            raise ValidationError(_("This value must be in the interval {imin} to {imax}.").format(imin=imin, imax=imax))
        return i

    def clean_python(self):
        """
        Compilation faults are reported.
        """
        python=self.cleaned_data["python"]
        errs=""
        try:
            ast=compile(python,'<string>', 'exec')
        except SyntaxError as e:
            errs+=str(e)
        except ValueError as e:
            errs+=str(e)
        if errs:
            raise ValidationError(errs)
        return python

    def clean_summary(self):
        """
        Checks that the summary is the name of a file in the
        subdirectory summaries; if the file does not exist, the
        file .template_en.rst is copied to the given file name.
        """
        summary=self.cleaned_data["summary"]
        if not summary.endswith(".rst"):
            summary+=".rst"
        target=os.path.join(SUMMARY_DIR, summary)
        if not os.path.isfile(target):
            with open(os.path.join(SUMMARY_DIR,'.template_en.rst')) as infile:
                with open(target,"w") as outfile:
                    outfile.write(infile.read())
        assert (os.path.isfile(target))
        return summary
            
                          

exp0/templates/expRecord.html
{% extends 'base.html' %}
{% load i18n %}

{% block htmlHeader %}
<script type="text/javascript" src="/static/remoteLab.js"></script>
<script src="/static/codemirror/codemirror.js"></script>
<link rel="stylesheet" href="/static/codemirror/codemirror.css"/>
<script src="/static/codemirror/mode/python/python.js"></script>
<link rel="stylesheet" href="/static/jsxgraph/distrib/jsxgraph.css"/>
<script src="/static/jsxgraph/distrib/jsxgraphcore.js"></script>
{% endblock %}

{% block title %}
{% trans "EYES17 experiments' record" %}
{% endblock %}

{% block content %}
<h1>
  {% trans "EYES17 experiments' record:" %}
  <span class="expTitle">"{{er.paramSet.exp.title}}"</span>
  ({{er.whenCreated}})
</h1>
<div>
  <h2>
    <span class="btn" onclick="stdoutCp()">
      {% trans 'Copy to Clipboard' %}
    </span>
    {% trans 'Standard output ... and its automatic plot' %}
  </h2>
  <textarea id="stdout" rows="26" cols="40" disabled="disabled">{{er.stdout}}</textarea>
  <div id="plot"></div>
  <script type="text/javascript">
    // to be called when #plot is defined
    stdoutPlot();
  </script>
</div>
<div>
  <h2>{% trans 'System error output' %}</h2>
  <textarea id="stderr" rows="3" cols="40" disabled="disabled">{{er.stderr}}</textarea>
</div>
<div>
  <h2>{% trans 'Video record' %}</h2>
  <video src="{{er.videoUrl}}" controls>
    {% trans 'Your browser does not manage the element <code>video</code>.' %}
  </video>
</div>

{% endblock %}

exp0/templates/expRecordRow.html
{% load i18n %}
	<tr id="row_experiment_{{er.pk}}">
	  <td>
	    {% trans 'Experiment' %}
	    &laquo;&nbsp;{{er.paramSet.exp.title}}&nbsp;&raquo;
	    <br/>
	    {% trans 'Parameter set' %}
	    &laquo;&nbsp;{{er.paramSet.name}}&nbsp;&raquo;
	  </td>
	  <td>{{er.whenCreated}}</td>
	  <td>{{er.paramSet.widgetReadOnly}}</td>
	  <td>
	    <div class="btn" onclick="deleteExpRecord({{er.pk}})">
	      {% trans 'Delete' %}
	    </div>
	    <a class="btn" target="_expWindow"
	       title="{% trans 'click here to open another window with the data' %}"
	       href="/exp0/viewExpRecord?date={{er.whenCreated|date:'c'|urlencode}}">
	      {% trans 'View' %}
	    </a>
	  </td>
	</tr>

exp0/templates/experimentform.html
{% load i18n %}
<div id="expform" class="hidableContainer">
  {% if experiments %}
  <h1 class="toggleBtn">{% trans 'New experiment' %}</h1>
  {% endif %}
  <form method="post" id="expForm" {% if experiments %}class="hidable"{% endif %}>
    {% csrf_token %}
    <table class="experiment">
      <tr class="title">
	<th><label for="id_title">{% trans 'Title:' %}</label></th>
	<td colspan="3">
	  {{ ef.title.errors }}
	  <input type="text" name="title" maxlength="140" required id="id_title" value="{{ef.title.value|default_if_none:''}}"/>
	</td>
	<th><label for="id_summary">{% trans 'Summary:' %}</label></th>
	<td colspan="3">
	  {{ ef.summary.errors }}
	  <input type="text" name="summary" maxlength="25" required id="id_summary" value="{{ef.summary.value|default_if_none:''}}"/>
	</td>
      </tr>
      <tr>
	<th><label for="id_sessionDuration">{% trans 'Session<br/>Timeslot (s):' %}</label></th>
	<td>
	  {{ ef.sessionDuration.errors }}
	  <input type="number" name="sessionDuration" required id="id_sessionDuration" style="width: 5em" value="{{ef.sessionDuration.value}}"/>
	</td>
	<th><label for="id_channels">{% trans 'Channels:' %}</label></th>
	<td>
	  {{ ef.channels.errors }}
	  <input type="text" name="channels" maxlength="50" required id="id_channels" value="{{ef.channels.value|default_if_none:''}}"/>
	</td>
	<th><label for="id_duration">{% trans 'Experiment duration (s):' %}</label></th>
	<td>
	  {{ ef.duration.errors }}
	  <input type="number" name="duration" step="any" required id="id_duration"  style="width: 5em" value="{{ef.duration.value|default_if_none:''}}"/>
	</td>
	<th><label for="id_nInterval">{% trans 'Intervals:' %}</label></th>
	<td>
	  {{ ef.nInterval.errors }}
	  <input type="number" name="nInterval" required id="id_nInterval"  style="width: 5em" value="{{ef.nInterval.value|default_if_none:''}}"/>
	</td>
      </tr>
      <tr>
	<th style="width: 80px;"><label for="id_python">
	    {% trans 'Python:' %}
	    <p class="pythonParams">
	      {% trans "the source contains the experiment's parameters symbols, as constant values." %}
	    </p>
	    {% if params %}
	    <hr style="width: 60%; background-color: orange; margin: auto;"/>
	    <p class="pythonParams">
	      {% trans 'List of symbols:' %}
	    </p>
	    <ul class="pythonParams">
	      {% for p in params %}
	      <li>{{p.symbol}}</li>
	      {% endfor %}
	    </ul>
	    {% endif %}
	</label></th>
	<td colspan="7">
	  {{ ef.python.errors }}
	  <textarea class="python" name="python" cols="90" rows="10" required id="id_python">{{ef.python.value|default_if_none:''}}</textarea>
	</td>
      </tr>
      <tr><td colspan="8"><div style="width: 16em; margin: 0 auto;">
	    {{ ef.non_field_errors }} 
	    <button id="submitButton" type="submit">
	      {% if experiments %}
	      {% trans 'Create experiment' %}
	      {% else %}
	      {% trans 'Save modifications' %}
	      {% endif %}
	    </button>
      </div></td></tr>
    </table>
    <input type="hidden" name="expId" value="{{expId}}"/>
  </form>
</div>

exp0/templates/manage.html
{% extends 'base.html' %}
{% load i18n %}

{% block htmlHeader %}
<script type="text/javascript" src="/static/manage.js"></script>
<script src="/static/codemirror/codemirror.js"></script>
<link rel="stylesheet" href="/static/codemirror/codemirror.css"/>
<script src="/static/codemirror/mode/python/python.js"></script>
{% endblock %}

{% block title %}
{% trans "Welcome to EYES17 experiments" %}
{% endblock %}

{% block content %}
{% if experiments %}
<h1>{% trans "Available experiments" %}</h1>
{% for e in experiments %}
<table class="experiment hidableContainer">
  <tr class="title">
    <th colspan="8" class="toggleBtn">
      {{e.title}}
      <div class="active-{{e.active}}" title="active = {{e.active}}"></div>
    </th>
    <td rowspan="6" class="hidable actions">
      <h1>{% trans "Actions" %}</h1>
      <h2 class="edit" data-exp-id="{{e.pk}}">{% trans "Edit" %}</h2>
      <h2 class="active" data-exp-id="{{e.pk}}">{% trans "(in)Activate" %}</h2>
      <h2 class="dupli" data-exp-id="{{e.pk}}">{% trans "Duplicate" %}</h2>
      <h2 class="delete" data-exp-id="{{e.pk}}">{% trans "Delete" %}</h2>
    </td>
  </tr>
  <tr class="summary hidable">
    <td colspan="8">
      <b>{{e.summary}}</b>
      <a class="viewRst btn" href="viewSummary?rst={{e.summary}}" target="_rstViewer_" title="{% trans 'View this file, rendered as styled HTML in another window or tab.' %}">{% trans 'View' %}</a>
      <a class="downloadRst btn" href="dlSummary?rst={{e.summary}}" title="{% trans 'Download the source ReSructuredText file to modify it in a suitable editor.' %}">{% trans 'Download' %}</a>
    </td>
  </tr>
  <tr class="otherdata hidable">
    <th>{% trans 'Session timeslot (s):' %}</th><td>{{e.sessionDuration}}</td>
    <th>{% trans 'Channels:' %}</th><td>{{e.channels}}</td>
    <th>{% trans 'Experiment duration (s):' %}</th><td>{{e.duration}}</td>
    <th>{% trans 'Intervals:' %}</th><td>{{e.nInterval}}</td>
  </tr>
  <tr class="parameters hidable">
    <th>{% trans 'Parameters' %}</th>
    <td class="parameters" colspan="7">
      {% for p in e.params %}
      <div class="parameter btn" data-id="{{p.pk}}" data-symbol="{{p.symbol}}" data-minval="{{p.minval}}" data-maxval="{{p.maxval}}" data-option="{{p.option}}" data-comment="{{p.comment}}" onclick="editParam(this)" title="{% trans 'Edit parameter' %} {{p.symbol}}">
	{{p.symbol}}
      </div>
      {% endfor %}
      &nbsp;&nbsp;&nbsp;
      <div class="parameter btnPlus" data-exp="{{e.pk}}" data-id="" onclick="editParam(this)" title="{% trans 'Create a new parameter' %}">
	++
      </div>
     
    </td>
  </tr>
  <tr class="title hidable"><th colspan="8">{% trans 'Python code' %}</th></tr>
  <tr class="code hidable">
    <td colspan="8">
      <textarea class="python readonly">{{e.python}}</textarea>
    </td>
  </tr>
</table>
{% endfor %}
{% endif %}

{% include "experimentform.html" %}

<form id="h" method="post" style="display:none;">
  <!-- this hidden form posts the expId of an experiment we want to edit -->
  {% csrf_token %}
  <input type="text" name="expId2edit" value=""/>
</form>

<div id="paramDialog" style="display: none;">
  <input type="hidden" name="id" />
  <input type="hidden" name="exp" />
  <table>
    <tr><th>{% trans 'Symbol:' %}</th>
      <td><input type="text" name="symbol" /></td>
    </tr>
    <tr><th>{% trans 'Minimum value:' %}</th>
      <td><input type="text" name="minval" /></td>
    </tr>
    <tr><th>{% trans 'Maximum value:' %}</th>
      <td><input type="text" name="maxval" /></td>
    </tr>
    <tr><th>{% trans 'Option:' %}</th>
      <td><input type="text" name="option" /></td>
    </tr>
    <tr>
      <td colspan="2">
	<h2>{% trans 'Comments:' %}</h2>
	<textarea name="comment" rows="4" cols="40"></textarea>
      </td>
    </tr>
  </table>
</div>

{% endblock %}