exp0/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^manage', manage, name='manage'),
    url(r'^viewSummary', viewSummary, name='viewSummary'),
    url(r'^dlSummary', dlSummary, name='dlSummary'),
    url(r'^activateExperiment', activateExperiment, name='activateExperiment'),
    url(r'^deleteExperiment', deleteExperiment, name='deleteExperiment'),
    url(r'^dupliExperiment', dupliExperiment, name='dupliExperiment'),
    url(r'^setParameter', setParameter, name='setParameter'),
    url(r'^delParameter', delParameter, name='delParameter'),
    url(r'^delRecord', delRecord, name='delRecord'),
    url(r'^remoteLab', remoteLab, name='remoteLab'),
    url(r'^recordParams', recordParams, name='recordParams'),
    url(r'^readParams', readParams, name='readParams'),
    url(r'^imageWebcam', imageWebcam, name='imageWebcam'),
    url(r'^programWithParams', programWithParams, name='programWithParams'),
    url(r'^deleteExpRecord', deleteExpRecord, name='deleteExpRecord'),
    url(r'^viewExpRecord', viewExpRecord, name='viewExpRecord'),
    url(r'^listExpRecords', listExpRecords, name='listExpRecords'),
]

mensu/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

from .views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/profile/$', makeProfile, name="makeProfile"),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^exp0/', include('exp0.urls')),
    url(r'^$', home, name='home'),
    url(r'^about', about, name='about'),
    url(r'^manual', manual, name='manual'),
    url(r'^license', license, name='license'),
    url(r'^activate/(?P<uidb64>[\w]+)-(?P<token>[-:\w]+)', activate, name='activate'),
#    url(r'', p404, name="404"),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mensu/forms.py
from django.utils.translation import gettext as _
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

import os
from PIL import Image

from .settings import BASE_DIR

_max_size=(300,400)

class ProfileForm(forms.Form):

    first_name=forms.CharField(max_length=30, label=_('Your first name'))
    last_name=forms.CharField(max_length=30, label=_('Your last name'))
    email=forms.EmailField(label=_('Your e-mail address'))
    image=forms.FileField(
        label=_('A small image as avatar (max-size: {w} x {h} px)').format(
            w=_max_size[0], h=_max_size[1]),
        required=False
    )

    def clean_image(self):
        image=self.cleaned_data['image']
        if image==None:
            return image # this field is not required
        im=None
        try:
            im=Image.open(image)
        except:
            raise ValidationError(_("'{}' was not recognized as an image file. Check the file's type.").format(image))
        if im.size[0]>_max_size[0] or im.size[1] > _max_size[1]:
            raise ValidationError(_("The size of the image '{i}' is {iw} x {ih} px, which is bigger than the maximum allowed size: {w} x {h} px.").format(
                i=image, iw=im.size[0], ih=im.size[1], w=_max_size[0], h=_max_size[1]))
        return image
    

mensu/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.sites.shortcuts import get_current_site
from allauth.account.models import EmailAddress
from django.contrib.auth.models import User, Group
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.core.mail import EmailMessage
from django.contrib.auth import authenticate, login
from allauth.account.models import EmailAddress

import os

from .tokens import account_activation_token
from .forms import ProfileForm
from exp0.models import ImageUser
from mensu.settings import MEDIA_URL

import mensu.version


def home(request):
    return render(
        request, 'home.html',
        {
        }
    )

def p404(request):
    return render(
        request, '404.html',
        context={
            "path": request.path
        },
        status=404,
    )

def about(request):
    return render( request, 'about.html', {"version": mensu.version})

def license(request):
    return render(request, 'license.html', {
        "license" : open("/usr/share/common-licenses/GPL-3").read(),
        "version": mensu.version,
    })

def manual(request):
     return render( request, 'manual.html', {})
   
def makeProfile(request):
    """
    Specific actions when some user has signed up, or ...
    """
    if request.method=="POST":
        form=ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            ## save the image
            print ("GRRRR request.FILES=", request.FILES)
            image=request.FILES.get('image',"")
            imageUsers=ImageUser.objects.filter(user=request.user)
            if imageUsers:
                # an image exists already for this user:
                # remove the older image and save the newest one
                imageUser=imageUsers[0]
                if image:
                    if os.path.isfile(imageUser.image.path):
                        os.remove(imageUser.image.path)
                    imageUser.image=image
                imageUser.save()
            else:
                # record a new image for this user
                if image:
                    imageUser=ImageUser(user=request.user, image=image)
                else:
                    imageUser=ImageUser(user=request.user)
                imageUser.save()
            ## save the other data to user's table
            request.user.first_name=form.cleaned_data["first_name"]
            request.user.last_name=form.cleaned_data["last_name"]
            request.user.email=form.cleaned_data["email"]
            request.user.save()
            ## save email to account/email table
            email=EmailAddress.objects.get(user=request.user)
            if email.email!=form.cleaned_data["email"]:
                email.email=form.cleaned_data["email"]
                email.verified=False
                email.primary=False
                email.save()
                return sendConfirmation(request, form)
            else:
                # the email has not changed in the account/email
                # send a confirmation e-mail if account/email is not verified
                if not email.verified:
                    return sendConfirmation(request, form)
        else:
            return render( request, 'profile.html', {
                "form": form,
            })         
    else:
        uploaded_file_url = ""
    images=ImageUser.objects.filter(user=request.user)
    account_emails=EmailAddress.objects.filter(email=request.user.email)
    if not account_emails:
        account_email=EmailAddress(email=request.user.email, user=request.user)
        account_email.save()
    else:
        account_email=account_emails[0]
    email=account_email
    if images:
        image=images[0].image
    else:
        image=None
    form=ProfileForm({
        "first_name": request.user.first_name,
        "last_name": request.user.last_name,
        "email": request.user.email,
    })
    ### Check whether we can subscribe this user to the group "visitor":
    if request.user.first_name and request.user.last_name and image and email.verified:
        ## whe have a profile sufficient to subscribe the user as visitor
        visitor = Group.objects.get(name='visitor') 
        visitor.user_set.add(request.user)
    return render( request, 'profile.html', {
        "form": form,
        "email": email,
        "image": str(image),
        "media_url": MEDIA_URL,
    })

def sendConfirmation(request, form):
    """
    sends a confirmation email
    @param request the request context of a user
    @param form other data coming from the form filled in accounts/profile/
    """
    user=request.user
    current_site = get_current_site(request)
    mail_subject = 'Activate your MENSU account.'
    uid=urlsafe_base64_encode(force_bytes(user.pk))
    token=account_activation_token.make_token(user)
    message = render_to_string('confirmation_email.html', {
        'user': user,
        'domain': current_site.domain,
        'uid': uid,
        'token': token,
    })
    to_email = form.cleaned_data.get('email')
    email = EmailMessage(
        mail_subject, message, to=[to_email]
    )
    email.send()
    return HttpResponse('Please confirm your email address to complete the registration')


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        ## validate the user's Email address
        emailAddress=EmailAddress.objects.get(user=user)
        emailAddress.verified=True
        emailAddress.primary=True
        emailAddress.save()
        login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        # return redirect('home')
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')
    

mensu/templates/about.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'About MENSU' %}{% endblock %}

{% block content %}
<h2>{% trans 'This is MENSU,' %} version {{version.upper}}.{{version.lower}}</h2>
<p>{% trans 'Codename:' %} {{version.codename}}</p>

{% endblock %}

mensu/templates/base.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>
      {% block title %}
      {% trans 'Base HTML title' %}
      {% endblock %}
    </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" type="text/css" href="/static/base.css"/>
    <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css" />
    <link rel="stylesheet" type="text/css" href="/static/admin/css/dashboard.css" />
    <link rel="stylesheet" type="text/css" href="/static/jquery-ui/css/smoothness/all.css" />
    <script type="text/javascript" src="/static/jquery/jquery.js"></script>
    <script type="text/javascript" src="/static/jquery-ui/jquery-ui.js"></script>
    {% block htmlHeader %}
    <!-- no default HTML header extensions there -->
    {% endblock %}
    <script type="text/javascript" src="/static/base.js"></script>
  </head>
  <body>
    {% block nav %}
    <div id="nav">
      <!-- User data, with user-related links, like "logout" -->
      <input type="hidden" id="userpk" value="{{user.pk}}"/>
      <div class="ddRight">
	{% if user.is_authenticated %}
	<div id="userData">
	  <p class="name">{{user.first_name}} {{user.last_name}}</p>
	  {% if user.groups.all %}
	  <ul>
	    {% for g in user.groups.all %}
	    <li>{{g}}</li>
	    {% endfor %}
	  </ul>
	  {% else %}
	  <!-- user is authenticated, but belongs to no group: she must update her profile! -->
	<div id="userData">
	  <p class="name">{% trans 'Update your profile!' %}</p>
	</div>
	  {% endif %}
	</div>
	<div class="dropdown-content">
	  <a href="/accounts/profile/">
	    {% trans 'Modify your<br/>profile settings' %}
	  </a>
	  <a href="/accounts/logout/">{% trans 'Log out' %}</a>
	</div>
	{% else %}
	<div id="userData">
	  <p class="name"> {% trans 'Enter the website...' %}</p>
	</div>
	<div class="dropdown-content">
	  <a href="/accounts/login/">{% trans 'Login' %}</a>
	  <a href="/accounts/signup">{% trans 'Create<br/>an account' %}</a>
	</div>
	{% endif %}
      </div>

      <div class="dropdown">
	<div  class="dropbtn middleButton">
	  <a href="/">{% trans 'Welcome page' %}</a>
	</div>
      </div>
      <!-- links to other working pages -->
      <div class="dropdown">
	<div  class="dropbtn middleButton">
	  {% trans 'Experiments' %}
	</div>
	<div class="dropdown-content">
	  <a href="/exp0/remoteLab" class="ifgroup" data-group="visitor">
	    {% trans 'Access the remote experient' %}
	  </a>
	  <a href="/exp0/manage" class="ifgroup" data-group="scientist">
	    {% trans 'Manage my experiments' %}
	  </a>
	</div>
      </div>
      
      <!-- links to help, etc. -->
      <div class="dropdown">
	<div  class="dropbtn middleButton">
	  {% trans 'Help' %}
	</div>
	<div class="dropdown-content">
	  <a href="/about">{% trans 'About ...' %} </a>
	  <a href="/license">{% trans 'License' %}</a>
	  <a href="/manual">{% trans 'User manual' %}</a>
	</div>
	
      </div>
      
      <div class="clearBoth"> </div>
    </div>
    
    <input type="hidden" id="thegroups" name="thegroups" value="{{user.groups.all}}"/>
    {% endblock %}
    <div id=bodyContent>
    {% block content %}
    {% endblock %}
    </div>
    <div id=footerContent>
    {% block footer %}
    {% endblock %}
    </div>
  </body>
</html>

mensu/templates/confirmation_email.html
{% load i18n %}
{% autoescape off %}
{% blocktrans %}
Hello {{ user.username }}, somebody has requested a confirmation e-mail
for the service MENSU provided by the server {{ domain }}; if this
request does not come from you, you can safely disregard this message.

Please click on the link below to confirm your registration,
{% endblocktrans %}

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

mensu/templates/home.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
{% trans 'Welcome to EYES17 experiments' %}
{% endblock %}

{% block content %}
<h1>{% trans 'Welcome to the application MENSU' %}</h1>
<p>
  {% blocktrans %}This application allows visitors to make experiments remotely.
  Depending on your status, you can access different pages.{% endblocktrans %}
</p>
<dl>
  <dt>{% trans 'Not authenticated guest' %}</dt>
  <dd>
    {% blocktrans %}When you are not yet authenticated, you can visit the home page
    (this page), create an account (as visitor) and read more about
    this web site's goal.{% endblocktrans %}
  </dd>
  <dt>{% trans 'Visitor' %}</dt>
  <dd>
    {% blocktrans %}When you are registered as a visitor, you can access more pages
    in this web site, the most interesting pages are:{% endblocktrans %}
    <ul>
      <li>
	{% blocktrans %}The experiment page: there, you can schedule a time slot to
	drive remotely the active experiment.{% endblocktrans %}
      </li>
      <li>
	{% blocktrans %}The results pages: for every experiment which you ordered
	remotely, there are data available for you: recordered measurements,
	and a short video file which shows the experiment running.{% endblocktrans %}
      </li>
      <li>
	{% blocktrans %}A collection of archived experiments: these are experiments
	which were prepared by the <b>scientists</b> in cherge of the server,
	which are not active at the time of the web request.{% endblocktrans %}
      </li>
      <li>
	{% blocktrans %}An asynchronous message system, and other communication
	media to exchange ideas between visitors and scientists{% endblocktrans %}
      </li>
    </ul>
  </dd>
  <dt>{% trans 'Scientist' %}</dt>
  <dd>
    <p>
      {% blocktrans %}A scientist can access all the contents above. She must first
      be a visitor, an request a subscription as scientist. This subscription
      cannot be done but when the website is served locally: that means
      that a scientist must have a physical access to the web server,
      which is also the computer which drives the experiments.{% endblocktrans %}
    </p>
    <p>
      {% blocktrans %}As a scientist, you can create the demonstrations and
      experiments which will be available remotely from the server.{% endblocktrans %}
    </p>
  </dd>
</dl>
{% endblock %}

mensu/templates/license.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'About MENSU' %}{% endblock %}

{% block content %}
<h1>{% trans "License's summary" %}</h1>
<p class="license">
  {% trans 'MENSU is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.' %}
</p>
<p class="license">
    {% trans 'This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.' %}
</p>
<p class="license">
    {% trans 'You should have received a copy of the GNU General Public License
    along with this program.  If not, see &lt;<a href="http://www.gnu.org/licenses/" target="_license">http://www.gnu.org/licenses/</a>&gt;.' %}
</p>
<h1>{% trans 'Owner and copyright' %}</h1>
<p class="license">
  {{version.copyright}}
</p>
<h1>{% trans 'The complete text of the license' %}</h1>
<pre class="license">{{license}}</pre>
{% endblock %}

mensu/templates/manual.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'MENSU User Manual' %}{% endblock %}

{% block content %}
<h1>{% trans 'User Manual' %}</h1>

{% endblock %}

mensu/templates/profile.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
{% trans 'Your profile' %}
{% endblock %}


{% block content %}
<div id="welcomeUser">
<h1>{% trans 'Welcome' %} {{user}}</h1>
{% if user.groups.all %}
<!-- the user has been at least subscribed to one group -->
<p>{% trans 'Your profile is currently complete, you are member of the group(s):' %}</p>
<ul>
{% for g in user.groups.all %}
<li>{{g}}</li>
{% endfor %}
</ul>
{% trans 'You can still modify your profile below.' %}
{% else %}
<p>
  {% blocktrans %}
  Please make your profile more complete, as we must know whether
  you are a robot, or somebody able to be granted the "visitor"
  permission.
  {% endblocktrans %}
</p>
{% endif %}
</div>
<hr style="margin: 10px;"/>
<form method="post" enctype="multipart/form-data" >
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit"
	 {% if email.verified %}
	 value="{% trans 'Validate' %}"
	 {% else %}
	 value="{% trans 'Validate and post confirmation e-mail' %}"
	 {% endif %}
	 />
</form>
<div id="hiddenMessage">{% trans 'Choose new image?' %}</div>

<script type="text/javascript">
  if ("{{image}}" != "None"){
  $("label[for='id_image']").html("<img src='{{media_url}}/{{image}}' alt='my image' style='height: 120px;'/>");
  var d= $("<div>").text($("#hiddenMessage").text());
  d.insertBefore($("#id_image"));
  }
</script>

{% endblock %}